### ISSUE TITLE
Replace Moq with NSubstitute

### ISSUE THREAD

**Issue by undrivendev** [undrivendev/template-webapi-aspnet#2]
I seems that Moq is now adware: https://github.com/moq/moq/issues/1372

It's necessary to move to NSubstitute.

**Comment by Creastoff** [comment]
Albert Monteiro has produced this repository with the required patterns to replace Moq with NSubstitute.
https://github.com/AlbertoMonteiro/moq-to-nsubstitute/tree/main

Bare in mind there are still some patterns missing (some of which have been raised as issues in the repo) so you may have to make adjustments depending on your usage of Moq.

I have also writtten the below tool which leverages these patterns to automatically replace instances of Moq with NSubstitute.

https://github.com/Creastoff/Moqstitute
